body:
  - type: markdown
    attributes:
      value: |
        <!-- tea-guestbook -->
name: "☕ Take a mug (Tea Guestbook)"
description: "Thanks for stopping by. Want a cup of tea to go?"
title: "☕ A cup of tea to-go for @username"
labels: ["tea-mug"]

- type: markdown
  attributes:
    value: |
      You can ignore the **@_____**. I’ll fill it in when the issue automatically closes. ☺️

body:
  - type: markdown
    attributes:
      value: |
        <!-- TEA_GUESTBOOK -->
        Thanks for stopping by. Pick a tea + a quick check-in 🌿

  - type: dropdown
    id: tea
    attributes:
      label: Which flavor of tea would you like?
      options:
        - matcha
        - lavender latte
        - chai
        - green peach tea
        - yerba mate (my favorite 😋)
    validations:
      required: true

  - type: dropdown
    id: mood
    attributes:
      label: How are you?
      options:
        - Great
        - Good
        - Meh
        - Not so great
    validations:
      required: true
