name: "☕ Take a mug (Tea Guestbook)"
description: "Thanks for stopping by. Want a cup of tea to go?"
title: "☕ A cup of tea to-go for @username"
labels: ["tea-mug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for stopping by. Pick a tea + a quick check-in 🌿

  - type: dropdown
    id: tea
    attributes:
      label: Which flavor of tea would you like?
      options:
        - Matcha
        - Lavender latte
        - Chai
        - Green peach tea
        - "Yerba mate (my favorite 😋)"
    validations:
      required: true

  - type: dropdown
    id: mood
    attributes:
      label: How are you?
      options:
        - Great
        - Good
        - Meh
        - Not so great
    validations:
      required: true
